name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 12 * * 3'
    - cron: '0 22 * * 5'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java_version: [11, 13, 17]
  
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK ${{ matrix.java_version }}
      if: ${{ matrix.java_version }} != 13
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java_version }}
        distribution: 'temurin'
      
    - name: Set up JDK 13
      if: ${{ matrix.java_version }} == 13
      uses: AdoptOpenJDK/install-jdk@v1
      with:
        version: '13'
        architecture: x64
      
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '7.3'

    - name: Build and run tests with Gradle Wrapper
      run: gradle build
